### ISSUE TITLE
Unable to Run Project

### ISSUE THREAD

**Issue by theparadox1083** [zzzeek/python_web_conf_2023#1]
I sincerely apologize as I'm not familiar with building python projects or using setuptools. When I attempt to run the commands to install the project via pip `pip install .`,  there are errors thrown from what I understand to be setuptools. From some forum posts, it seems like there were some changes in setuptools 69.0.0 that result in this kind of error. Unfortunately, I don't seem to be able to resolve the issue by using setuptools 68.2.2 (and setting requires = ["setuptools==68.2.2"] in pyproject.toml) - I receive the same errors. I've tried under Windows CLI, WSL2, and Linux and always eventually get down to the same errors. I am running Python 3.10 and pip 24.0. I've tried using setuptools 68.2.2, 69.1.1 and 69.2.0 in the venv and all have the same result below.
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sliderepl@ https://github.com/zzzeek/sliderepl/archive/refs/heads/master.zip (from sqlalchemy-mini-tutorial-2023==0.0.1)
  Using cached https://github.com/zzzeek/sliderepl/archive/refs/heads/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      /tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `license = 'MIT'`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:76: _MissingDynamic: `keywords` defined outside of `pyproject.toml` is ignored.
      !!
      
              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:
      
              `keywords = ['']`
      
              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `keywords` is listed as `dynamic`.
      
              https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
      
              To prevent this problem, you can list `keywords` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************
      
      !!
        _handle_missing_dynamic(dist, project_table)
      /tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:83: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
        corresp(dist, value, root_dir)
      Traceback (most recent call last):
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/_virtualenv.py", line 22, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 631, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 69, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 57, in apply
          _apply_project_table(dist, config, root_dir)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 83, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/tmp/pip-build-env-euwmpr1s/overlay/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 184, in _license
          _set_config(dist, "license", val["text"])
      KeyError: 'text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I've tried listing 'license' and 'keywords' as dynamic, I tried downloading and building sliderepl and received similar errors regarding 'license' and 'keywords' but receive new errors and feel like I'm out of my depth.

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Traceback (most recent call last):
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/home/user/Projects/python_web_conf_2023/.venv/lib/python3.10/site-packages/_virtualenv.py", line 22, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 653, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 131, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 156, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 204, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 242, in _expand_all_dynamic
          obtained_dynamic = {
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 243, in <dictcomp>
          field: self._obtain(dist, field, package_dir)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 292, in _obtain
          self._ensure_previously_set(dist, field)
        File "/tmp/pip-build-env-_kwg6fq0/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 268, in _ensure_previously_set
          raise OptionError(msg)
      distutils.errors.DistutilsOptionError: No configuration found for dynamic 'license'.
      Some dynamic fields need to be specified via `tool.setuptools.dynamic`
      others must be specified via the equivalent attribute in `setup.py`.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I imagine this was built for the conference so I understand if it is no longer being maintained.

Thank you.

**Comment by zzzeek** [comment]
the problem was in sliderepl.  run it again without any code changes, should work now
