### ISSUE TITLE
sliderepl fail to run 

### ISSUE THREAD

**Issue by zseda** [zzzeek/python_web_conf_2023#2]
When I follow the Readme commands and run
```
sliderepl 01_engine_usage.py

```
I get the following error message regardless of which command I enter. Thank you
```
% presentation mode is now ON
% SQL echo is now ON
%%
%% Running Deck: slides/00_talking.py
%%
%% This is an interactive Python prompt.
%% Enter "?" for command list.
%% Commands always begin with a ! symbol
%% Advance slides by pressing "enter",
%% or entering the "!n" or "!next" command.
%% Quit out of this deck by entering the "!q" or "!quit" command.

>>> 
Traceback (most recent call last):
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/bin/sliderepl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/lib/python3.11/site-packages/sliderepl/main.py", line 93, in main
    deck.run(options.script, **vars(options))
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/lib/python3.11/site-packages/sliderepl/core.py", line 535, in run
    console.interact(deck.banner if _goto is None else "")
  File "/usr/lib/python3.11/code.py", line 227, in interact
    line = self.raw_input(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/lib/python3.11/site-packages/sliderepl/core.py", line 674, in readfunc
    if len(tokens) != len(inspect.getargspec(fn)[0]):
                          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?% presentation mode is now ON
% SQL echo is now ON
%%
%% Running Deck: slides/00_talking.py
%%
%% This is an interactive Python prompt.
%% Enter "?" for command list.
%% Commands always begin with a ! symbol
%% Advance slides by pressing "enter",
%% or entering the "!n" or "!next" command.
%% Quit out of this deck by entering the "!q" or "!quit" command.

>>> 
Traceback (most recent call last):
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/bin/sliderepl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/lib/python3.11/site-packages/sliderepl/main.py", line 93, in main
    deck.run(options.script, **vars(options))
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/lib/python3.11/site-packages/sliderepl/core.py", line 535, in run
    console.interact(deck.banner if _goto is None else "")
  File "/usr/lib/python3.11/code.py", line 227, in interact
    line = self.raw_input(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeynep/repos/github/python_web_conf_2023/.venv/lib/python3.11/site-packages/sliderepl/core.py", line 674, in readfunc
    if len(tokens) != len(inspect.getargspec(fn)[0]):
                          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**Comment by zseda** [comment]
I used 3.11 since it was suggested in Installation guidelines. However, I had to downgrade to 3.10 to run the code/slides. Because the function that gives the error , `inspect.getargspec()` , was removed in Python 3.11.
